name: "Adding DB/TB to DMS task using terraform"
on:
  pull_request:
    branches:
      - main
    paths:
      - 'auditing_configs/data_audit_config_file.json'
permissions:
  contents: read
  pull-requests: write
env:
  TF_LOG: INFO
  AWS_REGION: ${{ secrets.AWS_REGION }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get changed files
        id: changed-files
        run: |
          echo "::set-output name=files::$(git diff --name-only "${{ github.event.before }}" "${{ github.event.after }}" --diff-filter=AM -- 'auditing_configs/data_audit_config_file.json')"

      - name: Request Review
        if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
        run: |
          echo "This pull request requires approval before deployment."
          echo "Assigned reviewers will need to review and approve the changes."

      - name: Check Review Approval
        if: github.event_name == 'pull_request' && github.event.action == 'synchronize'
        run: |
          reviews=$(gh pr review-list --json state | jq -r '.[].state')
          if [[ $reviews == *"APPROVED"* ]]; then
            echo "Pull request approved. Proceeding with deployment."
          else
            echo "Pull request not approved. Exiting."
            exit 1
          fi

      - name: Sync file to S3 and Trigger Glue Job
        if: github.event_name == 'pull_request' && github.event.action == 'synchronize'
        run: |
          aws s3 cp auditing_configs/data_audit_config_file.json s3://${{ secrets.AWS_S3_BUCKET }}/path/to/destination/
          aws glue start-job-run --job-name analytics-data-audit-testing-final
